openapi: 3.2.0
info:
  title: Fast Reject Face Match Suggestion API
  version: 0.1.0
tags:
- name: RejectFaceMatchSuggestion
paths:
  /rejectFaceMatchSuggestion:
    post:
      summary: Reject Face Match Suggestion Endpoint
      description: Mark suggestion as rejected so it does not appear again.
      operationId: reject_face_match_suggestion_endpoint_rejectFaceMatchSuggestion_post
      requestBody:
        content:
          application/json:
            schema:
              additionalProperties: true
              type: object
              title: Body
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - RejectFaceMatchSuggestion
components:
  schemas:
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
