openapi: 3.2.0
info:
  title: Fast Get Project Custom Tag Categories API
  version: 0.1.0
tags:
- name: GetProjectCustomTagCategories
paths:
  /getProjectCustomTagCategories:
    get:
      summary: Get Project Custom Tag Categories Endpoint
      description: Returns all custom tag categories and their default options for a project.
      operationId: get_project_custom_tag_categories_endpoint_getProjectCustomTagCategories_get
      parameters:
      - name: projectId
        in: query
        required: true
        schema:
          type: string
          title: Projectid
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - GetProjectCustomTagCategories
components:
  schemas:
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
