openapi: 3.2.0
info:
  title: Fast Get Attendee Registration Page Layout API
  version: 0.1.0
tags:
- name: GetAttendeeRegistrationPageLayout
paths:
  /getAttendeeRegistrationPageLayout:
    get:
      summary: Get Attendee Registration Page Layout Endpoint
      description: 'Organiser: get the registration page layout for a project. Requires auth.'
      operationId: get_attendee_registration_page_layout_endpoint_getAttendeeRegistrationPageLayout_get
      parameters:
      - name: projectId
        in: query
        required: true
        schema:
          type: integer
          title: Projectid
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - GetAttendeeRegistrationPageLayout
components:
  schemas:
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
