openapi: 3.2.0
info:
  title: Fast Delete Upload Link API
  version: 0.1.0
tags:
- name: DeleteUploadLink
paths:
  /deleteUploadLink:
    delete:
      summary: Delete Upload Link Endpoint
      operationId: delete_upload_link_endpoint_deleteUploadLink_delete
      parameters:
      - name: id
        in: query
        required: true
        schema:
          type: string
          title: Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - DeleteUploadLink
components:
  schemas:
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
