openapi: 3.2.0
info:
  title: Fast Send To Recipient API
  version: 0.1.0
tags:
- name: SendToRecipient
paths:
  /sendToRecipient:
    post:
      summary: Send To Recipient Endpoint
      description: "API endpoint for sending emails to recipients.\n\nValidates user permissions, extracts request parameters, and calls\nthe send_to_recipient function with the necessary data.\n\nReturns:\n    Flask response: JSON response with success message or error details"
      operationId: send_to_recipient_endpoint_sendToRecipient_post
      requestBody:
        content:
          application/json:
            schema:
              additionalProperties: true
              type: object
              title: Body
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - SendToRecipient
components:
  schemas:
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
