openapi: 3.2.0
info:
  title: Fast Create Upload Link API
  version: 0.1.0
tags:
- name: CreateUploadLink
paths:
  /createUploadLink:
    post:
      summary: Create Upload Link Endpoint
      operationId: create_upload_link_endpoint_createUploadLink_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUploadLinkRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - CreateUploadLink
components:
  schemas:
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    CreateUploadLinkRequest:
      properties:
        projectId:
          type: integer
          title: Projectid
        label:
          anyOf:
          - type: string
          - type: 'null'
          title: Label
        photographerId:
          anyOf:
          - type: string
          - type: 'null'
          title: Photographerid
        location:
          anyOf:
          - type: string
          - type: 'null'
          title: Location
        color:
          anyOf:
          - type: string
          - type: 'null'
          title: Color
        presetTags:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Presettags
        locked:
          anyOf:
          - type: boolean
          - type: 'null'
          title: Locked
          default: false
        startsAt:
          anyOf:
          - type: string
          - type: 'null'
          title: Startsat
        endsAt:
          anyOf:
          - type: string
          - type: 'null'
          title: Endsat
      type: object
      required:
      - projectId
      title: CreateUploadLinkRequest
